#!/usr/bin/env bash

set -e

MPOWER_TARGET="ssloboda-power"
PROC_PATH_BASE="/proc/power/relay"

function usage {
    echo "Usage: outletctl <outlet number | device> <on | off | toggle>"
}

function set_power_state {
    local state="${1}"
    local number="${2}"
    local path=""
    path="${PROC_PATH_BASE}${number}"
    ssh "${MPOWER_TARGET}" "/bin/sh -c \"echo ${state} > ${path}\""
}

function toggle_power_state {
    local number="${1}"
    local path=""
    path="${PROC_PATH_BASE}${number}"
    ssh "${MPOWER_TARGET}" "/bin/sh -c \"echo 0 > ${path}; sleep 1; echo 1 > ${path}\""
}

function main {
    if [ $# -lt 2 ]; then
        usage
        exit 1
    fi

    local outlet="${1}"
    local action="${2}"

    if [[ "${outlet}" -lt 1 || "${outlet}" -gt 8 ]]; then
        echo "ERROR: Outlet must be between 1 and 8"
        usage
        exit 1
    fi

    case "${action}" in
        "on")
            set_power_state 1 "${outlet}"
            ;;
        "off")
            set_power_state 0 "${outlet}"
            ;;
        "toggle")
            toggle_power_state "${outlet}"
            ;;
        *)
            echo "ERROR: ${action} not a recognized action"
            usage
            exit 1
            ;;
    esac
}

main "$@"
